sudo: required

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

services:
  - docker

before_install:
  - docker build -t noroutine/template-react .

script:
  - true

after_success:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
  - docker tag noroutine/template-react noroutine/template-react:travis-${COMMIT}
  - docker push noroutine/template-react:travis-${COMMIT}